project:
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js

website:  
  repo-url: https://github.com/coatless-quarto/r-shinylive-demo
  repo-actions: [edit, issue]
  title: "Homepage"
  navbar:
    search: false
    left:
      - text: "Background: Residential Seggregation"
        file: template-r-shinylive.qmd
      - text: "MSP: Environmental Injustice"
        file: index.qmd
      - text: "Why Urban Green Spaces"
        file: R-shinylive-demo.qmd

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
    theme:
      - custom.css

